# Generated by Django 2.0.5 on 2018-06-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dppc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='dppc')),
                ('dppc_id', models.CharField(max_length=128)),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dppc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
