# Generated by Django 2.0.5 on 2018-07-12 06:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_dppc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.CharField(max_length=200)),
                ('Person', models.CharField(max_length=40)),
                ('DateOfComment', models.DateField(default=datetime.datetime.now)),
                ('Leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave.ApplyLeave')),
            ],
        ),
        migrations.AlterField(
            model_name='dppc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dppcs', to=settings.AUTH_USER_MODEL),
        ),
    ]
