# Generated by Django 2.0.5 on 2018-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20180713_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Acedemic',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='Maternity',
            field=models.IntegerField(default=135),
        ),
        migrations.AlterField(
            model_name='student',
            name='Medical',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Odinary',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='Paternity',
            field=models.IntegerField(default=15),
        ),
    ]
